version: 0.1
os: linux
files:
  - source: AspNetCoreWebApplication/build_output
    destination: /home/ubuntu/aspnetcoreapp
  - source: scripts/virtualhost.conf
    destination: /home/ubuntu/aspnetcoreapp
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_httpd
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
